version: "3.1"

services:
  api:
    container_name: to-do_api
    image: node:16
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    restart: always
    stdin_open: true
    tty: true
    command: bash
  db:
    container_name: to-do_database
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=tdp1503
